# Name of workflows
name: My Test Workflow

# Define the trigger event(s)
on: [push]

# Jobs run in parallel by default, each run steps in sequence
jobs:
  # Jobs to print something out
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, Github Action!"
  
  build-and-test:
    needs: [say-hello]
    runs-on: ubuntu-latest
    steps:
      # Use github/actions/checkout to check out this repo
      - name: Check out this repo
        uses: actions/checkout@v3

      # Install necessary packages
      - name: Install dependences
        run: sudo apt install -y build-essential python3

      # See where we are in the VM
      - run: pwd

      # Run our test
      - name: Run test
        run: python3 test.py

